### ISSUE TITLE
ERR_REQUIRE_ESM when using TypeScript

### ISSUE THREAD

**Issue by Spaxly** [revoltchat/revolt.js#42]
`
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/*/node_modules/revolt.js/dist/index.js from /home/*/Projects/*/src/util/client.js not supported.
Instead change the require of index.js in /home/*/Projects/*/src/util/client.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/*/Projects/*/src/util/client.js:13:21)
    at Object.<anonymous> (/home/*/Projects/*/src/index.js:3:18)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.5.0
`
When running with ts-node, this error is outputted.

**Comment by Rexogamer** [comment]
This is an issue with your code. You need to use ESM - more details [here](https://developers.revolt.chat/revolt_js_guide/discord_js_migration#the-basics).
