### ISSUE TITLE
TypeError: Cannot read property 'low' of undefined

### ISSUE THREAD

**Issue by kaname-png** [revoltchat/revolt.js#52]
The error comes from the method: https://github.com/revoltchat/revolt.js/blob/master/src/permissions/calculator.ts#L25

![image](https://user-images.githubusercontent.com/56084970/166081519-c3aa1a87-ea1c-4899-99dc-5a0e05c73126.png)

**Comment by insertish** [comment]
Resolved by https://github.com/revoltchat/revolt/issues/322.
