### ISSUE TITLE
bug: Error deleting a message after bot sends DM to user

### ISSUE THREAD

**Issue by ghost** [revoltchat/revolt.js#73]
### What happened?

Revolt.js 7 seems to not handle deleting messages using `message.delete()` or `channel.deleteMessages()` correctly after a DM is sent.

Error message:
```ts
/home/dumpling/Documents/Code/stationbot/packages/revolt.js/lib/cjs/classes/Message.js:96
        return __classPrivateFieldGet(this, _Message_collection, "f").getUnderlyingObject(this.id).authorId;
                                                                                                  ^

TypeError: Cannot read properties of undefined (reading 'authorId')
    at get authorId [as authorId] (/home/dumpling/Documents/Code/stationbot/packages/revolt.js/lib/cjs/classes/Message.js:96:99)
    at Timeout._onTimeout (/home/dumpling/Documents/Code/stationbot/packages/base/dist/index.js:244:53)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.7.0
```
Code is available [here](https://github.com/stationaryStation/stationbot-revolt/blob/a00f2c6387aeab880eda57b9ab420fdcb8c81ef3/packages/base/src/commands/fun/boop.ts)

Removing `message.delete()`/`channel.deleteMessages()` seems to fix the issue.

Currently using revolt.js `7.0.0-beta.1`. Built locally.

EDIT: Add version information

**Comment by stationaryStation** [comment]
Issue persists in revolt.js 7.0.0-beta.4

**Comment by MagnusHJensen** [comment]
Can't reproduce on revolt.js 7.0.0-beta.6. (_Built locally_)

**Comment by insertish** [comment]
Assuming this was fixed.
