### ISSUE TITLE
feature request: add ability for client to delete emojis

### ISSUE THREAD

**Issue by sudoker0** [revoltchat/revolt.js#86]
### What do you want to see?

In the latest version of the revolt.js npm package, which as of writing this issue is `7.0.0-beta.9`, the client can fetch and add emojis to an server (though the `fetchEmojis` and `createEmoji` method), but not delete the emojis. So adding the ability to delete emojis would help add more capabilities to the packages.

**Comment by MagnusHJensen** [comment]
Is this not already available on the message object?
https://github.com/revoltchat/revolt.js/blob/master/src/classes/Message.ts#L323

**Comment by Rexogamer** [comment]
This issue refers to creating custom emoji, not adding reactions

**Comment by maximierung** [comment]
> This issue refers to creating custom emoji, not adding reactions - see [here](https://github.com/revoltchat/revolt.js/blob/6eb6ddbc31632f55a0f6a39a00f9ae44507df8e1/src/classes/Server.ts#L689-L721)

What about the emoji object? [It contains the delete function.](https://github.com/revoltchat/revolt.js/blob/master/src/classes/Emoji.ts#L85)

**Comment by maximierung** [comment]
@insertish this can be closed. 👍

**Comment by insertish** [comment]
Thanks
